name: flutter_cicd_example
description: "An app to demonstrate how to set up an automated deployment system on Google Play"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: 3.3.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.1

flutter:
  uses-material-design: true
